Add str to ReadableBuffer types
adafruit/Adafruit_CircuitPython_Typing pull request #5
Opened 2022-02-26 06:23 UTC by prplz

`str` implements buffer. I came across this when my IDE complained about passing strings to `wifi.radio.connect`.
Some other types can be found by searching for `.buffer_p =` in the codebase but I'm not sure if/how they should be added.

2022-02-28 19:08 UTC, dhalbert reviewed
`str` is indexable, but it does not implement buffer protocol, because it does not represent access to a uniform array of memory locations: characters in a string can be single-byte, multi-byte, etc.

I think the fix here is to change the signature of `wifi.radio.connect()` to include `str` as an allowed type.

[Note also that this PR added `str` only to a comment, and not to the `ReadableBuffer` definition.]

2022-02-28 19:09 UTC, dhalbert requested changes
I think we should close this in favor of a documentation signature change.

2022-02-28 19:22 UTC, prplz commented
str implements buffer protocol: https://github.com/adafruit/circuitpython/blob/main/py/objstrunicode.c#L312, https://github.com/adafruit/circuitpython/blob/main/py/objstr.c#L1950

2022-02-28 19:47 UTC, dhalbert commented
> str implements buffer protocol: https://github.com/adafruit/circuitpython/blob/main/py/objstrunicode.c#L312, https://github.com/adafruit/circuitpython/blob/main/py/objstr.c#L1950

I didn't know that was true in the core. That is non-standard, and I'm not sure we want to continue that behavior. In CPython, `str` does not implement buffer protocol. E.g., in CPython, you can't do `memoryview('abc'). You can in MicroPytthon/CircuitPython, not sure we want to continue that. It's possible buffer protocol is possible due to some internal implementation considerations.

2022-02-28 19:54 UTC, prplz commented
Fair enough, I also found it odd that the connect method accepted a buffer instead of just str.

2022-02-28 19:55 UTC, closed without merging

2022-02-28 19:56 UTC, dhalbert commented
I think mainly this was an oversight in the type annotation work for `wifi`.

2022-03-04 00:59 UTC, anecdata commented
> Fair enough, I also found it odd that the connect method accepted a buffer instead of just str.

SSIDs can be any arbitrary bytes, no limitations in the specs.